site_name: Visualization
theme: mkdocs
pages: 
- Home: 'Index.md'
- User Guide:
    - 'Getting Started' : 'user_guide/Getting-Started.md'
    - 'Chart Options' : 'user_guide/Chart-Options.md'
    - 'Chart Color (Palette) Usage': 'user_guide/Chart-Color-(Palette)-Usage.md' #maybe under chart options
    - 'Customizing Look & Feel' : 'user_guide/Look-and-Feel.md'
    - 'Widget Serialization' : 'user_guide/Widget-Serialization.md'
    - 'Marshaller' : 'user_guide/Marshaller.md'
    - 'Developing Widgets' : 'user_guide/Developing-Widgets.md'
- FAQ: 'FAQ.md'
- Playground: 'The-Playground.md' #link to playground?
- Theme-Editor: 'Theme-Editor.md' #link to theme editor?
- Examples:
    - 'AMD Examples' : 'examples/AMD-Examples.md'
    - 'Non-AMD Examples' : 'examples/Non-AMD-Examples.md'
    - 'Marshaller Examples' : 'examples/Marshaller-Examples.md'
#https://github.com/mkdocs/mkdocs/issues/282 line numbers