site_name: Visualization
theme: mkdocs
pages: 
- Home: 'Index.md'
- User Guide:
    - 'Getting Started' : 'user_guide/Getting-Started.md'
    - 'Anatomy of a Widget' : 'user_guide/Anatomy-of-a-Widget.md'
    - 'Chart Color (Palette) Usage': 'user_guide/Chart-Color-(Palette)-Usage.md'
    - 'Widget Serialization' : 'user_guide/Widget-Serialization.md'
    - 'Marshaller' : 'user_guide/Marshaller.md'
    #- 'Developing Widgets' : 'user_guide/Developing-Widgets.md'
- FAQ: 'FAQ.md'
- Playground: 'The-Playground.md'
- Theme-Editor: 'Theme-Editor.md'
- Examples:
    - 'AMD Examples' : 'examples/AMD-Examples.md'
    - 'Non-AMD Examples' : 'examples/Non-AMD-Examples.md'
    - 'Marshaller Examples' : 'examples/Non-AMD-Examples.md'