site_name: Visualization
theme: mkdocs
pages: 
- Home: 'Index.md'
- User Guide:
    - 'Getting Started' : 'user_guide/Getting-Started.md'
    - 'Building from Sources' : 'user_guide/Building-from-sources.md'
    - 'Bower Releases' : 'user_guide/Bower-Releases.md'
    - 'Anatomy of a Widget' : 'user_guide/Anatomy-of-a-Widget.md'
    - 'Widget Serialization' : 'user_guide/Widget-Serialization.md'
    - 'Chart Color (Palette) Usage': 'user_guide/Chart-Color-(Palette)-Usage.md'
    - 'Marshaller' : 'user_guide/Marshaller.md'
- FAQ: 'FAQ.md'
- Playground: 'The-Playground.md'
- Theme-Editor: 'Theme-Editor.md'
- Examples: 'Examples.md'