class tmp {
***  ***  Combo ***  ***
    paletteID: { (): string;(_: string): Combo};
paletteID_exists: () => boolean;
stacked: { (): boolean;(_: boolean): Combo};
stacked_exists: () => boolean;
fillOpacity: { (): number;(_: number): Combo};
fillOpacity_exists: () => boolean;
stackType: { (): string;(_: string): Combo};
stackType_exists: () => boolean;
bulletSize: { (): number;(_: number): Combo};
bulletSize_exists: () => boolean;
bulletType: { (): string;(_: string): Combo};
bulletType_exists: () => boolean;
defaultType: { (): string;(_: string): Combo};
defaultType_exists: () => boolean;
types: { (): any[];(_: any[]): Combo};
types_exists: () => boolean;
charts: { (): widgetArray;(_: widgetArray): Combo};
charts_exists: () => boolean;
bundle.test.js:6294 ***  ***  CommonFunnel ***  ***
    fontSize: { (): number;(_: number): CommonFunnel};
fontSize_exists: () => boolean;
fontFamily: { (): string;(_: string): CommonFunnel};
fontFamily_exists: () => boolean;
fontColor: { (): html-color; (_: html-color): CommonFunnel};
fontColor_exists: () => boolean;
flip: { (): boolean;(_: boolean): CommonFunnel};
flip_exists: () => boolean;
reverseDataSorting: { (): boolean;(_: boolean): CommonFunnel};
reverseDataSorting_exists: () => boolean;
labelPosition: { (): string;(_: string): CommonFunnel};
labelPosition_exists: () => boolean;
showScrollbar: { (): boolean;(_: boolean): CommonFunnel};
showScrollbar_exists: () => boolean;
startDuration: { (): number;(_: number): CommonFunnel};
startDuration_exists: () => boolean;
Depth3D: { (): number;(_: number): CommonFunnel};
Depth3D_exists: () => boolean;
Angle3D: { (): number;(_: number): CommonFunnel};
Angle3D_exists: () => boolean;
useClonedPalette: { (): boolean;(_: boolean): CommonFunnel};
useClonedPalette_exists: () => boolean;
selectionMode: { (): string;(_: string): CommonFunnel};
selectionMode_exists: () => boolean;
selectionColor: { (): html-color; (_: html-color): CommonFunnel};
selectionColor_exists: () => boolean;
PropertyExt.ts:234 ***  ***  CommonRadar ***  ***
    fontSize: { (): number;(_: number): CommonRadar};
fontSize_exists: () => boolean;
fontFamily: { (): string;(_: string): CommonRadar};
fontFamily_exists: () => boolean;
fontColor: { (): html-color; (_: html-color): CommonRadar};
fontColor_exists: () => boolean;
lineWidth: { (): number;(_: number): CommonRadar};
lineWidth_exists: () => boolean;
lineOpacity: { (): number;(_: number): CommonRadar};
lineOpacity_exists: () => boolean;
dashedLineStyle: { (): number;(_: number): CommonRadar};
dashedLineStyle_exists: () => boolean;
yAxisBaselineColor: { (): html-color; (_: html-color): CommonRadar};
yAxisBaselineColor_exists: () => boolean;
axisFontSize: { (): number;(_: number): CommonRadar};
axisFontSize_exists: () => boolean;
yAxisFontColor: { (): string;(_: string): CommonRadar};
yAxisFontColor_exists: () => boolean;
yAxisTitle: { (): string;(_: string): CommonRadar};
yAxisTitle_exists: () => boolean;
yAxisTitleFontColor: { (): html-color; (_: html-color): CommonRadar};
yAxisTitleFontColor_exists: () => boolean;
yAxisTitleFontSize: { (): html-color; (_: html-color): CommonRadar};
yAxisTitleFontSize_exists: () => boolean;
axisLineWidth: { (): number;(_: number): CommonRadar};
axisLineWidth_exists: () => boolean;
marginLeft: { (): number;(_: number): CommonRadar};
marginLeft_exists: () => boolean;
marginRight: { (): number;(_: number): CommonRadar};
marginRight_exists: () => boolean;
marginTop: { (): number;(_: number): CommonRadar};
marginTop_exists: () => boolean;
marginBottom: { (): number;(_: number): CommonRadar};
marginBottom_exists: () => boolean;
showScrollbar: { (): boolean;(_: boolean): CommonRadar};
showScrollbar_exists: () => boolean;
startDuration: { (): number;(_: number): CommonRadar};
startDuration_exists: () => boolean;
yAxisAutoGridCount: { (): boolean;(_: boolean): CommonRadar};
yAxisAutoGridCount_exists: () => boolean;
yAxisGridPosition: { (): string;(_: string): CommonRadar};
yAxisGridPosition_exists: () => boolean;
yAxisMinimum: { (): any[];(_: any[]): CommonRadar};
yAxisMinimum_exists: () => boolean;
yAxisTitleOffset: { (): any[];(_: any[]): CommonRadar};
yAxisTitleOffset_exists: () => boolean;
yAxisDashLength: { (): any[];(_: any[]): CommonRadar};
yAxisDashLength_exists: () => boolean;
axisAlpha: { (): number;(_: number): CommonRadar};
axisAlpha_exists: () => boolean;
circularGrid: { (): boolean;(_: boolean): CommonRadar};
circularGrid_exists: () => boolean;
bulletSize: { (): number;(_: number): CommonRadar};
bulletSize_exists: () => boolean;
bulletType: { (): string;(_: string): CommonRadar};
bulletType_exists: () => boolean;
fillOpacity: { (): number;(_: number): CommonRadar};
fillOpacity_exists: () => boolean;
useClonedPalette: { (): boolean;(_: boolean): CommonRadar};
useClonedPalette_exists: () => boolean;
yAxisTickFormat: { (): string;(_: string): CommonRadar};
yAxisTickFormat_exists: () => boolean;
selectionColor: { (): html-color; (_: html-color): CommonRadar};
selectionColor_exists: () => boolean;
selectionMode: { (): string;(_: string): CommonRadar};
selectionMode_exists: () => boolean;
PropertyExt.ts:234 ***  ***  XYAxis ***  ***
    axisAutoGridCount: { (): boolean;(_: boolean): XYAxis};
axisAutoGridCount_exists: () => boolean;
axisGridPosition: { (): string;(_: string): XYAxis};
axisGridPosition_exists: () => boolean;
axisTickFormat: { (): string;(_: string): XYAxis};
axisTickFormat_exists: () => boolean;
axisGridPosition: { (): string;(_: string): XYAxis};
axisGridPosition_exists: () => boolean;
axisGridAlpha: { (): number;(_: number): XYAxis};
axisGridAlpha_exists: () => boolean;
PropertyExt.ts:234 ***  ***  CommonXY ***  ***
    backwardsCompatible: { (): boolean;(_: boolean): CommonXY};
backwardsCompatible_exists: () => boolean;
xAxes: { (): propertyArray;(_: propertyArray): CommonXY};
xAxes_exists: () => boolean;
yAxes: { (): propertyArray;(_: propertyArray): CommonXY};
yAxes_exists: () => boolean;
fontSize: { (): number;(_: number): CommonXY};
fontSize_exists: () => boolean;
fontFamily: { (): string;(_: string): CommonXY};
fontFamily_exists: () => boolean;
fontColor: { (): html-color; (_: html-color): CommonXY};
fontColor_exists: () => boolean;
lineWidth: { (): number;(_: number): CommonXY};
lineWidth_exists: () => boolean;
lineColor: { (): html-color; (_: html-color): CommonXY};
lineColor_exists: () => boolean;
lineOpacity: { (): number;(_: number): CommonXY};
lineOpacity_exists: () => boolean;
dashedLineStyle: { (): number;(_: number): CommonXY};
dashedLineStyle_exists: () => boolean;
showScrollbar: { (): boolean;(_: boolean): CommonXY};
showScrollbar_exists: () => boolean;
bulletSize: { (): number;(_: number): CommonXY};
bulletSize_exists: () => boolean;
bulletType: { (): string;(_: string): CommonXY};
bulletType_exists: () => boolean;
marginLeft: { (): number;(_: number): CommonXY};
marginLeft_exists: () => boolean;
marginRight: { (): number;(_: number): CommonXY};
marginRight_exists: () => boolean;
marginTop: { (): number;(_: number): CommonXY};
marginTop_exists: () => boolean;
marginBottom: { (): number;(_: number): CommonXY};
marginBottom_exists: () => boolean;
selectionColor: { (): html-color; (_: html-color): CommonXY};
selectionColor_exists: () => boolean;
selectionMode: { (): string;(_: string): CommonXY};
selectionMode_exists: () => boolean;
showCursor: { (): boolean;(_: boolean): CommonXY};
showCursor_exists: () => boolean;
useClonedPalette: { (): boolean;(_: boolean): CommonXY};
useClonedPalette_exists: () => boolean;
axisLineWidth: { (): number;(_: number): CommonXY};
axisLineWidth_exists: () => boolean;
axisAlpha: { (): number;(_: number): CommonXY};
axisAlpha_exists: () => boolean;
PropertyExt.ts:234 ***  ***  Funnel ***  ***
    paletteID: { (): string;(_: string): Funnel};
paletteID_exists: () => boolean;
neckHeightPercent: { (): number;(_: number): Funnel};
neckHeightPercent_exists: () => boolean;
neckWidthPercent: { (): number;(_: number): Funnel};
neckWidthPercent_exists: () => boolean;
PropertyExt.ts:234 ***  ***  Gantt ***  ***
    paletteID: { (): string;(_: string): Gantt};
paletteID_exists: () => boolean;
fontFamily: { (): string;(_: string): Gantt};
fontFamily_exists: () => boolean;
fontSize: { (): number;(_: number): Gantt};
fontSize_exists: () => boolean;
fontColor: { (): html-color; (_: html-color): Gantt};
fontColor_exists: () => boolean;
depth3D: { (): number;(_: number): Gantt};
depth3D_exists: () => boolean;
angle3D: { (): number;(_: number): Gantt};
angle3D_exists: () => boolean;
selectionMode: { (): string;(_: string): Gantt};
selectionMode_exists: () => boolean;
useClonedPalette: { (): boolean;(_: boolean): Gantt};
useClonedPalette_exists: () => boolean;
timePattern: { (): string;(_: string): Gantt};
timePattern_exists: () => boolean;
selectionColor: { (): html-color; (_: html-color): Gantt};
selectionColor_exists: () => boolean;
brightnessStep: { (): number;(_: number): Gantt};
brightnessStep_exists: () => boolean;
columnWidth: { (): number;(_: number): Gantt};
columnWidth_exists: () => boolean;
minPeriod: { (): string;(_: string): Gantt};
minPeriod_exists: () => boolean;
guides: { (): any[];(_: any[]): Gantt};
guides_exists: () => boolean;
PropertyExt.ts:234 ***  ***  Gauge ***  ***
    paletteID: { (): string;(_: string): Gauge};
paletteID_exists: () => boolean;
low: { (): number;(_: number): Gauge};
low_exists: () => boolean;
high: { (): number;(_: number): Gauge};
high_exists: () => boolean;
fontSize: { (): number;(_: number): Gauge};
fontSize_exists: () => boolean;
fontFamily: { (): string;(_: string): Gauge};
fontFamily_exists: () => boolean;
fontColor: { (): html-color; (_: html-color): Gauge};
fontColor_exists: () => boolean;
axisLineWidth: { (): number;(_: number): Gauge};
axisLineWidth_exists: () => boolean;
colorType: { (): string;(_: string): Gauge};
colorType_exists: () => boolean;
marginLeft: { (): number;(_: number): Gauge};
marginLeft_exists: () => boolean;
marginRight: { (): number;(_: number): Gauge};
marginRight_exists: () => boolean;
marginTop: { (): number;(_: number): Gauge};
marginTop_exists: () => boolean;
marginBottom: { (): number;(_: number): Gauge};
marginBottom_exists: () => boolean;
numBands: { (): number;(_: number): Gauge};
numBands_exists: () => boolean;
bandsColor: { (): any[];(_: any[]): Gauge};
bandsColor_exists: () => boolean;
bandsStartValue: { (): any[];(_: any[]): Gauge};
bandsStartValue_exists: () => boolean;
bandsEndValue: { (): any[];(_: any[]): Gauge};
bandsEndValue_exists: () => boolean;
bandsInnerRadius: { (): any[];(_: any[]): Gauge};
bandsInnerRadius_exists: () => boolean;
axisAlpha: { (): number;(_: number): Gauge};
axisAlpha_exists: () => boolean;
tickAlpha: { (): number;(_: number): Gauge};
tickAlpha_exists: () => boolean;
valueInterval: { (): number;(_: number): Gauge};
valueInterval_exists: () => boolean;
bottomText: { (): string;(_: string): Gauge};
bottomText_exists: () => boolean;
bottomTextYOffset: { (): number;(_: number): Gauge};
bottomTextYOffset_exists: () => boolean;
animatationDuration: { (): number;(_: number): Gauge};
animatationDuration_exists: () => boolean;
useClonedPalette: { (): boolean;(_: boolean): Gauge};
useClonedPalette_exists: () => boolean;
PropertyExt.ts:234 ***  ***  Line ***  ***
    paletteID: { (): string;(_: string): Line};
paletteID_exists: () => boolean;
smoothLines: { (): boolean;(_: boolean): Line};
smoothLines_exists: () => boolean;
stepLines: { (): boolean;(_: boolean): Line};
stepLines_exists: () => boolean;
bulletSize: { (): number;(_: number): Line};
bulletSize_exists: () => boolean;
bulletType: { (): string;(_: string): Line};
bulletType_exists: () => boolean;
PropertyExt.ts:234 ***  ***  Pie ***  ***
    paletteID: { (): string;(_: string): Pie};
paletteID_exists: () => boolean;
useClonedPalette: { (): boolean;(_: boolean): Pie};
useClonedPalette_exists: () => boolean;
fontSize: { (): number;(_: number): Pie};
fontSize_exists: () => boolean;
fontFamily: { (): string;(_: string): Pie};
fontFamily_exists: () => boolean;
fontColor: { (): html-color; (_: html-color): Pie};
fontColor_exists: () => boolean;
Depth3D: { (): number;(_: number): Pie};
Depth3D_exists: () => boolean;
Angle3D: { (): number;(_: number): Pie};
Angle3D_exists: () => boolean;
marginLeft: { (): number;(_: number): Pie};
marginLeft_exists: () => boolean;
marginRight: { (): number;(_: number): Pie};
marginRight_exists: () => boolean;
marginTop: { (): number;(_: number): Pie};
marginTop_exists: () => boolean;
marginBottom: { (): number;(_: number): Pie};
marginBottom_exists: () => boolean;
reverseDataSorting: { (): boolean;(_: boolean): Pie};
reverseDataSorting_exists: () => boolean;
holePercent: { (): number;(_: number): Pie};
holePercent_exists: () => boolean;
radius: { (): number;(_: number): Pie};
radius_exists: () => boolean;
pieAlpha: { (): any[];(_: any[]): Pie};
pieAlpha_exists: () => boolean;
labelPosition: { (): string;(_: string): Pie};
labelPosition_exists: () => boolean;
selectionMode: { (): string;(_: string): Pie};
selectionMode_exists: () => boolean;
selectionColor: { (): html-color; (_: html-color): Pie};
selectionColor_exists: () => boolean;
PropertyExt.ts:234 ***  ***  Polar ***  ***
    paletteID: { (): string;(_: string): Polar};
paletteID_exists: () => boolean;
PropertyExt.ts:234 ***  ***  Pyramid ***  ***
    paletteID: { (): string;(_: string): Pyramid};
paletteID_exists: () => boolean;
PropertyExt.ts:234 ***  ***  Scatter ***  ***
    paletteID: { (): string;(_: string): Scatter};
paletteID_exists: () => boolean;
scatterType: { (): string;(_: string): Scatter};
scatterType_exists: () => boolean;
}